### ISSUE TITLE
`name_mapping` checked against quoted type

### ISSUE THREAD

**Issue by eugenkleinschmidt** [sbrunner/jsonschema-gentypes#1137]
It seems that `name_mappings` stores name mappings unquoted but checked against a quoted type.  `type_.name()` returns a quoted string.
```python
def name(self) -> str:
        """
        Return what we need to use the type.
        """
        return f'"{self._name}"'
```

Maybe I missing something but for me it works only if change it to `type._unescape_name()`. Like that:

```python
if isinstance(type_, jsonschema_gentypes.NamedType) and type_.unescape_name() in name_mapping:
        type_.set_name(name_mapping[type_.unescape_name()])
```

My mapping:
```yaml
name_mapping: {
      _RelayboardmappingMappingsType: RelayBoardMappings,
      _RelayboardmappingMappingsTypeOneof0: RelayConnectionGroup,
      _RelayboardmappingMappingsTypeOneof1: RelayConnectionId
    }
```

You see it also when you print the mappings and the type: 
```python
print("Type Name:", type_.name(), "\nName Mappings:", name_mapping)
```
```
Type Name: "RelayBoardMappingConfig"
Name Mappings: {'_RelayboardmappingMappingsType': 'RelayBoardMappings', '_RelayboardmappingMappingsTypeOneof0': 'RelayConnectionGroup', '_RelayboardmappingMappingsTypeOneof1': 'RelayConnectionId'}
```
